PYTHON=/usr/bin/env python3
VENV=venv
ENTER_VENV=. ${VENV}/bin/activate

MAIN=./main.py
SEQ_GEN=sequence_generation.py
ENZIAN=enzian_descriptions.py

EVAL_SCRIPT=./evaluation.py
PLOT_SCRIPT=./plots.py

.PHONY: default
default: enzian_sequence.py

.PHONY: paper-results
paper-results: enzian_sequence.py plots/eval1_m2_p1.png plots/eval1_m2_p2.png plots/eval1_m2_p3.png results/eval2.csv

${VENV}: requirements.txt
	$(PYTHON) -m venv $@
	$(ENTER_VENV) && pip install -r requirements.txt

enzian_sequence.py: ${MAIN} ${SEQ_GEN} ${ENZIAN} | ${VENV}
	$(ENTER_VENV) && $(MAIN) -o $@ enzian

results/eval1_%_p1.csv results/eval1_%_p2.csv results/eval1_%_p3.csv: ${SEQ_GEN} ${ENZIAN} ${EVAL_SCRIPT} | ${VENV}
	$(ENTER_VENV) && $(EVAL_SCRIPT) --e1$*

results/eval2.csv : ${SEQ_GEN} ${ENZIAN} ${EVAL_SCRIPT} | ${VENV}
	$(ENTER_VENV) && $(EVAL_SCRIPT) --e2

results/eval3.txt: ${SEQ_GEN} ${ENZIAN} ${EVAL_SCRIPT} | ${VENV}
	$(ENTER_VENV) && $(EVAL_SCRIPT) --e3
# This is also generated by the above recipe
results/eval3_sequence.py: results/eval3.txt

plots/eval1_m1.png: results/eval1_m1_p1.csv results/eval1_m1_p2.csv results/eval1_m1_p2.csv ${PLOT_SCRIPT} | ${VENV}
	$(ENTER_VENV) && $(PLOT_SCRIPT) --m1
# This is also generated by the above recipe
plots/eval1_m1_Z3.png: plots/eval1_m1.png

plots/eval1_m2_p1.png: results/eval1_m2_p1.csv results/eval1_m2_p2.csv results/eval1_m2_p2.csv ${PLOT_SCRIPT} | ${VENV}
	$(ENTER_VENV) && $(PLOT_SCRIPT) --m2
# These are also generated by the above recipe
plots/eval1_m2_p2.png plots/eval1_m2_p3.png: plots/eval1_m2_p1.png

plots/eval1_m3_p1.png: results/eval1_m3_p1.csv results/eval1_m3_p2.csv results/eval1_m3_p2.csv ${PLOT_SCRIPT} | ${VENV}
	$(ENTER_VENV) && $(PLOT_SCRIPT) --m3
# These are also generated by the above recipe
plots/eval1_m3_p2.png plots/eval1_m3_p3.png: plots/eval1_m3_p1.png

plots/eval1_m4.png: results/eval1_m4_p1.csv results/eval1_m4_p2.csv results/eval1_m4_p2.csv ${PLOT_SCRIPT} | ${VENV}
	$(ENTER_VENV) && $(PLOT_SCRIPT) --m4

.PHONY: clean
clean:
	$(RM) set_events.txt
	$(RM) enzian_sequence.py

.PHONY: clean-results
clean-results:
	$(RM) results/*

.PHONY: clean-plots
clean-plots:
	$(RM) plots/*

.PHONY: clean-all
clean-all: clean clean-results clean-plots
